#!/usr/bin/env bash
# ═══════════════════════════════════════════════════════════════
# WarTab — Extension Builder
# Packages the extension for Chrome, Edge, and Firefox stores.
# All version info derived from git at build time.
# ═══════════════════════════════════════════════════════════════
# Usage:
#   bash extension/build.sh [chrome|edge|firefox|all]
#
# Output: dist/wartab-{browser}-{githash}.zip
# ═══════════════════════════════════════════════════════════════

set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(dirname "$HERE")"

# ── Derive build identity from git ──
GIT_HASH=$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo "unknown")
GIT_REV_COUNT=$(git -C "$ROOT" rev-list --count HEAD 2>/dev/null || echo "0")
GIT_DESCRIBE=$(git -C "$ROOT" describe --tags --always --dirty 2>/dev/null || echo "$GIT_HASH")
MANIFEST_VERSION="0.0.0.$GIT_REV_COUNT"

BUILD="${1:-all}"

# Clean stale dist artifacts
rm -rf "$ROOT/dist"

echo "  Git:      $GIT_HASH ($GIT_DESCRIBE)"
echo "  Revision: $GIT_REV_COUNT"
echo ""

# Files to include in all extension builds
FILES=(
  index.html
  style.css
  storage.js
  core.js
  app.js
  icon-picker.js
  uploads.js
  dragdrop.js
  manifest.json
  modules/
  static/
  icons/
)

build() {
  local name="$1" manifest_src="$2"
  local dist="$ROOT/dist/$name"
  local zipfile="$ROOT/dist/wartab-${name}-${GIT_HASH}.zip"
  rm -rf "$dist" "$zipfile"
  mkdir -p "$dist"

  echo "  Building $name..."

  # Copy all shared files
  for f in "${FILES[@]}"; do
    local src="$ROOT/$f"
    if [ -d "$src" ]; then
      mkdir -p "$dist/$f"
      cp -r "$src"/* "$dist/$f/"
    elif [ -f "$src" ]; then
      cp "$src" "$dist/"
    fi
  done

  # Use store-specific manifest (if provided)
  if [ -n "$manifest_src" ] && [ -f "$manifest_src" ]; then
    cp "$manifest_src" "$dist/manifest.json"
  fi

  # Inject numeric version into manifest (Chrome requires x.y.z.w)
  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' "s/\"version\": \".*\"/\"version\": \"$MANIFEST_VERSION\"/" "$dist/manifest.json"
    sed -i '' "s/\"version_name\": \".*\"/\"version_name\": \"$GIT_HASH\"/" "$dist/manifest.json"
  else
    sed -i "s/\"version\": \".*\"/\"version\": \"$MANIFEST_VERSION\"/" "$dist/manifest.json"
    sed -i "s/\"version_name\": \".*\"/\"version_name\": \"$GIT_HASH\"/" "$dist/manifest.json"
  fi

  # Write build-meta.js so the UI footer shows the git hash
  cat > "$dist/build-meta.js" <<METAEOF
// WarTab — build metadata (auto-generated by extension/build.sh)
WARTAB_BUILD = '$GIT_HASH';
METAEOF

  # Create zip
  cd "$dist"
  zip -r "$zipfile" . > /dev/null 2>&1
  local size=$(du -sh "$zipfile" | cut -f1)
  echo "  📦 $zipfile ($size)"
}

case "$BUILD" in
  chrome)
    build "chrome" ""
    ;;
  edge)
    build "edge" "$HERE/edge/manifest.json"
    ;;
  firefox)
    build "firefox" "$HERE/firefox/manifest.json"
    ;;
  all)
    echo "Building WarTab extension packages..."
    echo ""
    build "chrome" ""
    build "edge" "$HERE/edge/manifest.json"
    build "firefox" "$HERE/firefox/manifest.json"
    echo ""
    echo "Done! All packages in dist/"
    ls -lh "$ROOT"/dist/wartab-*.zip
    echo ""
    echo "To load: chrome://extensions → Developer mode → Load unpacked → select dist/{browser}/"
    ;;
  *)
    echo "Usage: bash extension/build.sh [chrome|edge|firefox|all]"
    exit 1
    ;;
esac
