/* ═══════════════════════════════════════════
   WarTab — Core Utilities & Constants
   Shared by app.js and all modules.
   Pure functions with no dependencies on app.js state.
   ═══════════════════════════════════════════ */

/* ── Card Type Modules registry ── */
const WARTAB_VERSION = 'dev';
var WARTAB_BUILD = '';
const CARD_MODULES = {};
function registerModule(type, module){
  CARD_MODULES[type]=module;
  // Auto-inject per-module CSS into <head> on registration
  if(module.css){
    var id='mod-css-'+type;
    if(!document.getElementById(id)){
      var s=document.createElement('style');s.id=id;s.textContent=module.css;
      document.head.appendChild(s);
    }
  }
}

/* ── Event Bus (Pub/Sub) ── */
// Lightweight pub/sub for targeted re-renders instead of calling renderAll().
// Subscribe with: var unsub = on('config:card:updated', fn)
// Fire with:      emit('config:card:updated', { cardId: '...' })
const _evBus={};
function on(ev,fn){if(!_evBus[ev])_evBus[ev]=[];_evBus[ev].push(fn);return function(){_evBus[ev]=_evBus[ev].filter(function(f){return f!==fn;});};}
function emit(ev,data){(_evBus[ev]||[]).forEach(function(fn){try{fn(data);}catch(e){console.error('[EventBus]',ev,e);}});}

/* ── Public API presets for API Poller ── */
const API_PRESETS = [
  { label:'GitHub Repo', url:'https://api.github.com/repos/warmbo/wartab', fields:[{label:'Stars',path:'stargazers_count'},{label:'Forks',path:'forks_count'},{label:'Issues',path:'open_issues_count'}], icon:'github' },
  { label:'Bitcoin Price', url:'https://api.coinbase.com/v2/prices/BTC-USD/spot', fields:[{label:'BTC/USD',path:'data.amount'}], icon:'bitcoin' },
  { label:'Ethereum Price', url:'https://api.coinbase.com/v2/prices/ETH-USD/spot', fields:[{label:'ETH/USD',path:'data.amount'}], icon:'bitcoin' },
  { label:'Dog API', url:'https://dog.ceo/api/breeds/image/random', fields:[{label:'Breed Image',path:'message'}], icon:'dog' },
  { label:'IP Info', url:'http://ip-api.com/json/', fields:[{label:'IP',path:'query'},{label:'ISP',path:'isp'},{label:'City',path:'city'},{label:'Country',path:'country'}], icon:'map-pin' },
  { label:'Random User', url:'https://randomuser.me/api/', fields:[{label:'Name',path:'results.0.name.first'},{label:'Country',path:'results.0.location.country'}], icon:'users' },
  { label:'Open-Meteo (NYC)', url:'https://api.open-meteo.com/v1/forecast?latitude=40.71&longitude=-74.01&current_weather=true', fields:[{label:'Temp °C',path:'current_weather.temperature'},{label:'Wind km/h',path:'current_weather.windspeed'}], icon:'cloud-sun' },
  { label:'Joke', url:'https://v2.jokeapi.dev/joke/Any?type=single', fields:[{label:'Joke',path:'joke'}], icon:'message-circle' },
  { label:'ISS Location', url:'http://api.open-notify.org/iss-now.json', fields:[{label:'Lat',path:'iss_position.latitude'},{label:'Lon',path:'iss_position.longitude'}], icon:'globe' },
  { label:'Nightscout CGM', url:'https://YOUR-SITE.herokuapp.com/api/v1/entries.json?count=1', fields:[{label:'Glucose',path:'0.sgv',format:'number'},{label:'Trend',path:'0.direction'},{label:'Time',path:'0.dateString'}], icon:'activity' },
  { label:'Uptime Robot', url:'https://api.uptimerobot.com/v2/getMonitors', fields:[{label:'Monitors',path:'monitors'}], icon:'activity' },
  { label:'Pi-hole Summary', url:'http://pi.hole/admin/api.php?summary', fields:[{label:'Queries',path:'dns_queries_today'},{label:'Blocked',path:'ads_blocked_today'},{label:'Percent',path:'ads_percentage_today',format:'percent'}], icon:'shield' },
  { label:'Speedtest Results', url:'https://www.speedtest.net/api/js/result/1', fields:[{label:'Download',path:'download'},{label:'Upload',path:'upload'},{label:'Ping',path:'ping'}], icon:'activity' },
  { label:'Docker Stats', url:'http://localhost:9323/containers/stats', fields:[{label:'Containers',path:'containers'}], icon:'container' },
  { label:'Home Assistant', url:'http://homeassistant.local:8123/api/states', fields:[{label:'States',path:'length'}], icon:'home' },
];

/* ── Icon data ── */

/**
 * Curated emoji dataset: [emoji, category, keywords]
 * ~500 emojis with CLDR short names for search.
 * Categories: smiley, people, nature, food, travel, objects, symbols, flags
 * Search filters by keywords (case-insensitive substring match).
 */
const EMOJI_DATA = [
  // Smileys & Emotion
  ['😀','smiley','grinning face|smile|happy|grin'],
  ['😃','smiley','grinning face with big eyes|smile|happy'],
  ['😄','smiley','grinning face with smiling eyes|smile|happy'],
  ['😁','smiley','beaming face with smiling eyes|smile|happy'],
  ['😆','smiley','grinning squinting face|smile|laugh'],
  ['😅','smiley','grinning face with sweat|smile|sweat'],
  ['🤣','smiley','rolling on the floor laughing|laugh|rofl'],
  ['😂','smiley','face with tears of joy|laugh|tears|cry'],
  ['🙂','smiley','slightly smiling face|smile'],
  ['🙃','smiley','upside-down face|smile|silly'],
  ['😉','smiley','winking face|wink|flirt'],
  ['😊','smiley','smiling face with smiling eyes|blush|smile'],
  ['😇','smiley','smiling face with halo|angel|innocent'],
  ['🥰','smiley','smiling face with hearts|love|heart'],
  ['😍','smiley','smiling face with heart-eyes|love|heart'],
  ['🤩','smiley','star-struck|star|excited'],
  ['😘','smiley','face blowing a kiss|kiss|love'],
  ['😗','smiley','kissing face|kiss'],
  ['😚','smiley','kissing face with closed eyes|kiss'],
  ['😙','smiley','kissing face with smiling eyes|kiss'],
  ['🥲','smiley','smiling face with tear|smile|cry'],
  ['😋','smiley','face savoring food|yum|food|delicious'],
  ['😛','smiley','face with tongue|tongue|silly'],
  ['😜','smiley','winking face with tongue|silly|joke'],
  ['🤪','smiley','zany face|crazy|silly'],
  ['😝','smiley','squinting face with tongue|silly|tongue'],
  ['🤑','smiley','money-mouth face|money|rich'],
  ['🤗','smiley','smiling face with open hands|hug'],
  ['🤭','smiley','face with hand over mouth|oops|shh'],
  ['🫢','smiley','face with open eyes and hand over mouth|shock|surprise'],
  ['🫣','smiley','face with peeking eye|peek|hide'],
  ['🤫','smiley','shushing face|shh|quiet|silence'],
  ['🤔','smiley','thinking face|think|ponder'],
  ['🫡','smiley','saluting face|salute|military'],
  ['🤐','smiley','zipper-mouth face|zip|silence'],
  ['🤨','smiley','face with raised eyebrow|skeptical|sus'],
  ['😐','smiley','neutral face|neutral|meh'],
  ['😑','smiley','expressionless face|blank|straight'],
  ['😶','smiley','face without mouth|silent|mute'],
  ['🫥','smiley','dotted line face|invisible|hide'],
  ['😏','smiley','smirking face|smirk|smug'],
  ['😒','smiley','unamused face|unamused|meh'],
  ['🙄','smiley','face with rolling eyes|roll|eyeroll'],
  ['😬','smiley','grimacing face|grimace|awkward'],
  ['😮‍💨','smiley','face exhaling|sigh|relief'],
  ['🤥','smiley','lying face|liar|pinocchio'],
  ['😌','smiley','relieved face|relieved|peace'],
  ['😔','smiley','pensive face|pensive|sad'],
  ['😪','smiley','sleepy face|sleepy|tired'],
  ['🤤','smiley','drooling face|drool|hungry'],
  ['😴','smiley','sleeping face|sleep|zzz'],
  ['😷','smiley','face with medical mask|mask|sick|ill'],
  ['🤒','smiley','face with thermometer|sick|fever'],
  ['🤕','smiley','face with head-bandage|hurt|injury'],
  ['🤢','smiley','nauseated face|sick|nausea|vomit'],
  ['🤮','smiley','face vomiting|vomit|sick'],
  ['🤧','smiley','sneezing face|sneeze|cold|sick'],
  ['🥵','smiley','hot face|sweat|hot|overheated'],
  ['🥶','smiley','cold face|freezing|ice|cold'],
  ['🥴','smiley','woozy face|dizzy|drunk'],
  ['😵','smiley','face with crossed-out eyes|dizzy|shock'],
  ['😵‍💫','smiley','face with spiral eyes|dizzy|hypnotized'],
  ['🤯','smiley','exploding head|mind blown|shock'],
  ['🤠','smiley','cowboy hat face|cowboy|western'],
  ['🥳','smiley','partying face|party|celebrate'],
  ['🥸','smiley','disguised face|disguise|incognito'],
  ['😎','smiley','smiling face with sunglasses|cool|sun'],
  ['🤓','smiley','nerd face|nerd|geek'],
  ['🧐','smiley','face with monocle|fancy|rich'],
  ['😕','smiley','confused face|confused|unsure'],
  ['🫤','smiley','face with diagonal mouth|confused|unsure'],
  ['😟','smiley','worried face|worry|concern'],
  ['🙁','smiley','slightly frowning face|frown|sad'],
  ['😮','smiley','face with open mouth|surprise|shock'],
  ['😯','smiley','hushed face|hush|surprise'],
  ['😲','smiley','astonished face|astonished|shock'],
  ['😳','smiley','flushed face|embarrassed|blush'],
  ['🥺','smiley','pleading face|puppy|begging|cute'],
  ['🥹','smiley','face holding back tears|tears|emotional'],
  ['😢','smiley','crying face|cry|tears'],
  ['😭','smiley','loudly crying face|cry|bawl|tears'],
  ['😤','smiley','face with steam from nose|frustrated|angry'],
  ['😡','smiley','pouting face|angry|mad'],
  ['😠','smiley','angry face|angry|mad'],
  ['🤬','smiley','face with symbols on mouth|cursing|swear'],
  ['😈','smiley','smiling face with horns|devil|evil'],
  ['👿','smiley','angry face with horns|devil|evil'],
  ['💀','smiley','skull|death|danger'],
  ['☠️','smiley','skull and crossbones|death|poison'],
  ['💩','smiley','pile of poo|poop|crap'],
  ['🤡','smiley','clown face|clown|carnival'],
  ['👹','smiley','ogre|monster|oni'],
  ['👺','smiley','goblin|monster'],
  ['👻','smiley','ghost|halloween|spooky'],
  ['👽','smiley','alien|ufo|space'],
  ['👾','smiley','alien monster|game|space invader'],
  ['🤖','smiley','robot|bot|automation'],
  ['😺','smiley','grinning cat|cat|smile'],
  ['😸','smiley','grinning cat with smiling eyes|cat|smile'],
  ['😹','smiley','cat with tears of joy|cat|laugh'],
  ['😻','smiley','smiling cat with heart-eyes|cat|love'],
  ['😼','smiley','cat with wry smile|cat|smirk'],
  ['😽','smiley','kissing cat|cat|kiss'],
  ['🙀','smiley','weary cat|cat|tired'],
  ['😿','smiley','crying cat|cat|cry|tears'],
  ['😾','smiley','pouting cat|cat|angry'],
  ['🙈','smiley','see-no-evil monkey|monkey|hide|shame'],
  ['🙉','smiley','hear-no-evil monkey|monkey|deaf'],
  ['🙊','smiley','speak-no-evil monkey|monkey|silent'],
  ['💌','smiley','love letter|love|romance|mail'],
  ['💘','smiley','heart with arrow|love|cupid'],
  ['💝','smiley','heart with ribbon|gift|love'],
  ['💖','smiley','sparkling heart|love|sparkle'],
  ['💗','smiley','growing heart|love|increase'],
  ['💓','smiley','beating heart|heartbeat|love'],
  ['💞','smiley','revolving hearts|love|recycle'],
  ['💕','smiley','two hearts|love'],
  ['💟','smiley','heart decoration|love'],
  ['❣️','smiley','heart exclamation|love|emphasis'],
  ['💔','smiley','broken heart|heartbreak|sad'],
  ['❤️‍🔥','smiley','heart on fire|passion|love'],
  ['❤️‍🩹','smiley','mending heart|heal|repair'],
  ['❤️','smiley','red heart|love|heart'],
  ['🩷','smiley','pink heart|love|heart'],
  ['🧡','smiley','orange heart|love|heart'],
  ['💛','smiley','yellow heart|love|heart'],
  ['💚','smiley','green heart|love|heart'],
  ['💙','smiley','blue heart|love|heart'],
  ['🩵','smiley','light blue heart|love|heart'],
  ['💜','smiley','purple heart|love|heart'],
  ['🤎','smiley','brown heart|love|heart'],
  ['🖤','smiley','black heart|love|dark'],
  ['🩶','smiley','gray heart|love|heart'],
  ['🤍','smiley','white heart|love|heart'],
  ['💋','smiley','kiss mark|kiss|lips'],
  ['💯','smiley','hundred points|100|perfect|score'],
  ['💢','smiley','anger symbol|angry|comic'],
  ['💥','smiley','collision|explosion|boom'],
  ['💫','smiley','dizzy|star|sparkle'],
  ['💦','smiley','sweat droplets|sweat|exercise'],
  ['💨','smiley','dashing away|run|speed|smoke'],
  ['🕳️','smiley','hole|void|dark'],
  ['💬','smiley','speech balloon|chat|talk|message'],
  ['🗯️','smiley','right anger bubble|angry|shout'],
  ['💭','smiley','thought balloon|think|idea'],
  ['💤','smiley','zzz|sleep|tired'],

  // People & Body
  ['👋','people','waving hand|wave|hello|bye'],
  ['🤚','people','raised back of hand|hand|stop'],
  ['🖐️','people','hand with fingers splayed|hand|stop'],
  ['✋','people','raised hand|hand|stop'],
  ['🖖','people','vulcan salute|spock|star trek'],
  ['🫱','people','rightwards hand|hand|right'],
  ['🫲','people','leftwards hand|hand|left'],
  ['🫳','people','palm down hand|hand|down'],
  ['🫴','people','palm up hand|hand|up'],
  ['👌','people','ok hand|ok|perfect'],
  ['🤌','people','pinched fingers|italy|gesture'],
  ['🤏','people','pinching hand|small|tiny'],
  ['✌️','people','victory hand|peace|v'],
  ['🤞','people','crossed fingers|luck|hope'],
  ['🫰','people','hand with index finger and thumb crossed|love|money'],
  ['🤟','people','love-you gesture|ily|rock'],
  ['🤘','people','sign of the horns|rock|metal'],
  ['🤙','people','call me hand|phone|call'],
  ['👈','people','backhand index pointing left|left|point'],
  ['👉','people','backhand index pointing right|right|point'],
  ['👆','people','backhand index pointing up|up|point'],
  ['🖕','people','middle finger|fuck you'],
  ['👇','people','backhand index pointing down|down|point'],
  ['☝️','people','index pointing up|up|point'],
  ['🫵','people','index pointing at the viewer|you|point'],
  ['👍','people','thumbs up|like|approve'],
  ['👎','people','thumbs down|dislike|disapprove'],
  ['✊','people','raised fist|power|solidarity'],
  ['👊','people','oncoming fist|punch|hit'],
  ['🤛','people','left-facing fist|punch'],
  ['🤜','people','right-facing fist|punch'],
  ['👏','people','clapping hands|applause|clap'],
  ['🙌','people','raising hands|celebrate|hooray'],
  ['🫶','people','heart hands|love|heart'],
  ['👐','people','open hands|open|hug'],
  ['🤲','people','palms up together|pray|beg'],
  ['🤝','people','handshake|agreement|deal'],
  ['🙏','people','folded hands|pray|please|thank you'],
  ['✍️','people','writing hand|write|author'],
  ['💅','people','nail polish|nail|care|fancy'],
  ['🤳','people','selfie|camera|phone'],
  ['💪','people','flexed biceps|muscle|strong|arm'],
  ['🦵','people','leg|kick|limb'],
  ['🦶','people','foot|step|limb'],
  ['👂','people','ear|hearing|listen'],
  ['🦻','people','ear with hearing aid|deaf|hearing'],
  ['👃','people','nose|smell|scent'],
  ['🧠','people','brain|mind|intelligence'],
  ['🫀','people','anatomical heart|heart|medical'],
  ['🫁','people','lungs|breathe|respiratory'],
  ['🦷','people','tooth|teeth|dental'],
  ['🦴','people','bone|skeleton'],
  ['👀','people','eyes|look|see'],
  ['👁️','people','eye|look|see'],
  ['👅','people','tongue|taste|mouth'],
  ['👄','people','mouth|lips|kiss'],
  ['👶','people','baby|infant|newborn'],
  ['🧒','people','child|kid|young'],
  ['👦','people','boy|male|child'],
  ['👧','people','girl|female|child'],
  ['🧑','people','person|adult'],
  ['👱','people','person with blond hair|blonde'],
  ['👨','people','man|male|adult'],
  ['🧔','people','man with beard|beard|facial hair'],
  ['👩','people','woman|female|adult'],
  ['🧓','people','older person|elderly|senior'],
  ['👴','people','old man|elderly|grandpa'],
  ['👵','people','old woman|elderly|grandma'],
  ['🙍','people','person frowning|frown|sad'],
  ['🙎','people','person pouting|pout|sad'],
  ['🙅','people','person gesturing no|no|deny|forbid'],
  ['🙆','people','person gesturing ok|ok|approve'],
  ['💁','people','person tipping hand|sassy|info'],
  ['🙋','people','person raising hand|question|raise'],
  ['🧏','people','deaf person|deaf|sign'],
  ['🙇','people','person bowing|bow|respect|sorry'],
  ['🤦','people','person facepalming|facepalm|frustrated'],
  ['🤷','people','person shrugging|shrug|dunno'],
  ['👮','people','police officer|cop|law'],
  ['🕵️','people','detective|sleuth|spy'],
  ['👷','people','construction worker|builder|hard hat'],
  ['🫅','people','person with crown|royal|king|queen'],
  ['🤴','people','prince|royal|crown'],
  ['👸','people','princess|royal|crown'],
  ['👳','people','person wearing turban|turban'],
  ['👲','people','person with skullcap|skullcap'],
  ['🧕','people','woman with headscarf|hijab|headscarf'],
  ['🤵','people','person in tuxedo|tux|suit|formal'],
  ['👰','people','person with veil|bride|wedding'],
  ['🤰','people','pregnant woman|pregnancy|baby'],
  ['🫃','people','pregnant man|pregnancy'],
  ['🫄','people','pregnant person|pregnancy'],
  ['🤱','people','breastfeeding|baby|milk'],
  ['👼','people','baby angel|angel|heaven'],
  ['🎅','people','santa claus|christmas|holiday'],
  ['🤶','people','mrs claus|christmas|holiday'],
  ['🦸','people','superhero|hero|marvel|dc'],
  ['🦹','people','supervillain|villain|evil'],
  ['🧙','people','mage|wizard|magic'],
  ['🧚','people','fairy|magic|fantasy'],
  ['🧛','people','vampire|dracula|halloween'],
  ['🧜','people','merperson|mermaid|merman'],
  ['🧝','people','elf|fantasy|lotr'],
  ['🧞','people','genie|magic|lamp'],
  ['🧟','people','zombie|undead|halloween'],
  ['💆','people','person getting massage|spa|relax'],
  ['💇','people','person getting haircut|hair|barber'],
  ['🚶','people','person walking|walk|hiking'],
  ['🧍','people','person standing|stand|wait'],
  ['🧎','people','person kneeling|kneel|pray'],
  ['🏃','people','person running|run|sprint'],
  ['💃','people','woman dancing|dance|party'],
  ['🕺','people','man dancing|dance|disco'],
  ['🕴️','people','person in suit levitating|hover|business'],
  ['👯','people','people with bunny ears|bunny|party'],
  ['🧖','people','person in steamy room|sauna|steam'],
  ['🧗','people','person climbing|climb|mountaineer'],
  ['🤸','people','person cartwheeling|gymnastics|flip'],
  ['⛷️','people','skier|ski|winter'],
  ['🏂','people','snowboarder|snowboard|winter'],
  ['🏄','people','person surfing|surf|wave'],
  ['🚣','people','person rowing boat|row|boat'],
  ['🏊','people','person swimming|swim|pool'],
  ['🤽','people','person playing water polo|water polo'],
  ['🤾','people','person playing handball|handball'],
  ['🧘','people','person in lotus position|yoga|meditate'],

  // Animals & Nature
  ['🐶','nature','dog face|dog|pet|puppy'],
  ['🐱','nature','cat face|cat|pet|kitten'],
  ['🐭','nature','mouse face|mouse|rat'],
  ['🐹','nature','hamster face|hamster|pet'],
  ['🐰','nature','rabbit face|rabbit|bunny'],
  ['🦊','nature','fox face|fox|animal'],
  ['🐻','nature','bear face|bear|animal'],
  ['🐼','nature','panda face|panda|bear'],
  ['🐻‍❄️','nature','polar bear|bear|arctic'],
  ['🐨','nature','koala face|koala|bear'],
  ['🐯','nature','tiger face|tiger|animal'],
  ['🦁','nature','lion face|lion|animal'],
  ['🐮','nature','cow face|cow|animal'],
  ['🐷','nature','pig face|pig|animal'],
  ['🐸','nature','frog face|frog|animal'],
  ['🐵','nature','monkey face|monkey|animal'],
  ['🐒','nature','monkey|monkey|animal'],
  ['🐔','nature','chicken|chicken|bird'],
  ['🐧','nature','penguin|penguin|bird'],
  ['🐦','nature','bird|bird|tweet'],
  ['🐤','nature','baby chick|chick|bird'],
  ['🦅','nature','eagle|bird|raptor'],
  ['🦆','nature','duck|duck|bird'],
  ['🦉','nature','owl|owl|bird|wise'],
  ['🦇','nature','bat|bat|vampire'],
  ['🐺','nature','wolf|wolf|animal'],
  ['🐗','nature','boar|boar|animal'],
  ['🐴','nature','horse face|horse|pony'],
  ['🦄','nature','unicorn|unicorn|fantasy'],
  ['🐝','nature','honeybee|bee|insect'],
  ['🪱','nature','worm|worm|animal'],
  ['🐛','nature','bug|bug|insect'],
  ['🦋','nature','butterfly|butterfly|insect'],
  ['🐌','nature','snail|snail|slow'],
  ['🐞','nature','lady beetle|ladybug|insect'],
  ['🐜','nature','ant|ant|insect'],
  ['🪰','nature','fly|fly|insect'],
  ['🪳','nature','cockroach|roach|insect'],
  ['🦗','nature','cricket|cricket|insect'],
  ['🕷️','nature','spider|spider|insect'],
  ['🦂','nature','scorpion|scorpion|animal'],
  ['🐢','nature','turtle|turtle|slow'],
  ['🐍','nature','snake|snake|reptile'],
  ['🦎','nature','lizard|lizard|reptile'],
  ['🦖','nature','t-rex|dinosaur|t-rex'],
  ['🦕','nature','sauropod|dinosaur|brontosaurus'],
  ['🐙','nature','octopus|octopus|ocean'],
  ['🦑','nature','squid|squid|ocean'],
  ['🦐','nature','shrimp|shrimp|seafood'],
  ['🐠','nature','tropical fish|fish|ocean'],
  ['🐟','nature','fish|fish|ocean'],
  ['🐡','nature','blowfish|blowfish|fish'],
  ['🐬','nature','dolphin|dolphin|ocean'],
  ['🐳','nature','spouting whale|whale|ocean'],
  ['🐋','nature','whale|whale|ocean'],
  ['🦈','nature','shark|shark|ocean'],
  ['🐊','nature','crocodile|crocodile|reptile'],
  ['🐅','nature','tiger|tiger|big cat'],
  ['🐆','nature','leopard|leopard|big cat'],
  ['🦓','nature','zebra|zebra|animal'],
  ['🦍','nature','gorilla|gorilla|ape'],
  ['🦧','nature','orangutan|orangutan|ape'],
  ['🐘','nature','elephant|elephant|animal'],
  ['🦣','nature','mammoth|mammoth|extinct'],
  ['🦛','nature','hippopotamus|hippo|animal'],
  ['🦏','nature','rhinoceros|rhino|animal'],
  ['🐪','nature','camel|camel|desert'],
  ['🐫','nature','two-hump camel|camel|desert'],
  ['🦒','nature','giraffe|giraffe|animal'],
  ['🦘','nature','kangaroo|kangaroo|aussie'],
  ['🦬','nature','bison|bison|buffalo'],
  ['🐃','nature','water buffalo|buffalo|animal'],
  ['🐂','nature','ox|ox|bull'],
  ['🐄','nature','cow|cow|animal'],
  ['🐎','nature','horse|horse|race'],
  ['🐖','nature','pig|pig|animal'],
  ['🐏','nature','ram|ram|sheep'],
  ['🐑','nature','ewe|sheep|lamb'],
  ['🦙','nature','llama|llama|alpaca'],
  ['🐐','nature','goat|goat|animal'],
  ['🦌','nature','deer|deer|animal'],
  ['🐕','nature','dog|dog|pet'],
  ['🐩','nature','poodle|dog|pet'],
  ['🦮','nature','guide dog|service dog'],
  ['🐕‍🦺','nature','service dog|assistance dog'],
  ['🐈','nature','cat|cat|pet'],
  ['🐈‍⬛','nature','black cat|cat|unlucky'],
  ['🐓','nature','rooster|rooster|chicken'],
  ['🦃','nature','turkey|turkey|thanksgiving'],
  ['🦤','nature','dodo|dodo|extinct'],
  ['🦚','nature','peacock|peacock|bird'],
  ['🦜','nature','parrot|parrot|bird'],
  ['🦢','nature','swan|swan|bird'],
  ['🦩','nature','flamingo|flamingo|bird'],
  ['🕊️','nature','dove|dove|peace|bird'],
  ['🐇','nature','rabbit|rabbit|bunny'],
  ['🦝','nature','raccoon|raccoon|trash panda'],
  ['🦨','nature','skunk|skunk|stink'],
  ['🦡','nature','badger|badger|animal'],
  ['🦫','nature','beaver|beaver|animal'],
  ['🦦','nature','otter|otter|animal'],
  ['🦥','nature','sloth|sloth|slow'],
  ['🐁','nature','mouse|mouse|rat'],
  ['🐀','nature','rat|rat|pest'],
  ['🐿️','nature','chipmunk|chipmunk|squirrel'],
  ['🦔','nature','hedgehog|hedgehog|spiny'],
  ['🐾','nature','paw prints|paw|pet|animal'],
  ['🐉','nature','dragon|dragon|fantasy'],
  ['🐲','nature','dragon face|dragon|fantasy'],
  ['🌵','nature','cactus|desert|plant'],
  ['🎄','nature','christmas tree|christmas|holiday'],
  ['🌲','nature','evergreen tree|pine|tree'],
  ['🌳','nature','deciduous tree|tree|leaf'],
  ['🌴','nature','palm tree|palm|tropical'],
  ['🌱','nature','seedling|seed|plant|sprout'],
  ['🌿','nature','herb|leaf|plant|green'],
  ['☘️','nature','shamrock|clover|irish'],
  ['🍀','nature','four leaf clover|luck|clover'],
  ['🍁','nature','maple leaf|canada|fall'],
  ['🍂','nature','fallen leaf|autumn|fall'],
  ['🍃','nature','leaf fluttering in wind|leaf|wind'],
  ['🌺','nature','hibiscus|flower|hawaii'],
  ['🌸','nature','cherry blossom|flower|spring|sakura'],
  ['🌼','nature','blossom|flower|spring'],
  ['🌻','nature','sunflower|flower|sun'],
  ['🌹','nature','rose|flower|love|romance'],
  ['🌷','nature','tulip|flower|spring'],
  ['🌎','nature','globe showing americas|earth|globe|world'],
  ['🌍','nature','globe showing europe-africa|earth|globe|world'],
  ['🌏','nature','globe showing asia-australia|earth|globe|world'],
  ['🌕','nature','full moon|moon|night'],
  ['🌙','nature','crescent moon|moon|night'],
  ['🌞','nature','sun with face|sun|bright'],
  ['⭐','nature','star|star|rating'],
  ['🌟','nature','glowing star|star|sparkle'],
  ['💫','nature','dizzy|star|sparkle|twinkle'],
  ['☀️','nature','sun|sun|bright|light'],
  ['🌈','nature','rainbow|rain|lgbt|pride'],

  // Food & Drink
  ['🍇','food','grapes|grape|fruit'],
  ['🍈','food','melon|melon|fruit'],
  ['🍉','food','watermelon|melon|fruit'],
  ['🍊','food','tangerine|orange|fruit'],
  ['🍋','food','lemon|lemon|citrus'],
  ['🍌','food','banana|banana|fruit'],
  ['🍍','food','pineapple|pineapple|fruit'],
  ['🥭','food','mango|mango|fruit'],
  ['🍎','food','red apple|apple|fruit'],
  ['🍏','food','green apple|apple|fruit'],
  ['🍐','food','pear|pear|fruit'],
  ['🍑','food','peach|peach|butt'],
  ['🍒','food','cherries|cherry|fruit'],
  ['🍓','food','strawberry|strawberry|fruit'],
  ['🫐','food','blueberries|blueberry|fruit'],
  ['🥝','food','kiwi fruit|kiwi|fruit'],
  ['🍅','food','tomato|tomato|vegetable'],
  ['🫒','food','olive|olive|food'],
  ['🥥','food','coconut|coconut|fruit'],
  ['🥑','food','avocado|avocado|fruit'],
  ['🍆','food','eggplant|eggplant|aubergine'],
  ['🥔','food','potato|potato|food'],
  ['🥕','food','carrot|carrot|vegetable'],
  ['🌽','food','corn|corn|maize'],
  ['🌶️','food','hot pepper|pepper|spicy'],
  ['🫑','food','bell pepper|pepper|vegetable'],
  ['🥒','food','cucumber|cuke|vegetable'],
  ['🥬','food','leafy green|lettuce|salad'],
  ['🥦','food','broccoli|broccoli|vegetable'],
  ['🧄','food','garlic|garlic|cooking'],
  ['🧅','food','onion|onion|cooking'],
  ['🍄','food','mushroom|mushroom|fungus'],
  ['🥜','food','peanuts|peanut|nut'],
  ['🫘','food','beans|bean|legume'],
  ['🌰','food','chestnut|chestnut|nut'],
  ['🍞','food','bread|bread|toast'],
  ['🥐','food','croissant|croissant|french'],
  ['🥖','food','baguette bread|bread|french'],
  ['🫓','food','flatbread|bread|pita|naan'],
  ['🥨','food','pretzel|pretzel|snack'],
  ['🥯','food','bagel|bagel|breakfast'],
  ['🥞','food','pancakes|pancake|breakfast'],
  ['🧇','food','waffle|waffle|breakfast'],
  ['🧀','food','cheese wedge|cheese|dairy'],
  ['🍖','food','meat on bone|meat|bbq'],
  ['🍗','food','poultry leg|chicken|drumstick'],
  ['🥩','food','cut of meat|steak|meat'],
  ['🥓','food','bacon|bacon|breakfast'],
  ['🍔','food','hamburger|burger|fast food'],
  ['🍟','food','french fries|fries|fast food'],
  ['🍕','food','pizza|pizza|italian'],
  ['🌭','food','hot dog|hotdog|fast food'],
  ['🥪','food','sandwich|sandwich|lunch'],
  ['🌮','food','taco|taco|mexican'],
  ['🌯','food','burrito|burrito|mexican'],
  ['🫔','food','tamale|tamale|mexican'],
  ['🥙','food','stuffed flatbread|gyro|wrap'],
  ['🧆','food','falafel|falafel|middle eastern'],
  ['🥚','food','egg|egg|breakfast'],
  ['🍳','food','cooking|frying|egg|pan'],
  ['🥘','food','shallow pan of food|paella|cooking'],
  ['🍲','food','pot of food|stew|soup'],
  ['🫕','food','fondue|fondue|cheese'],
  ['🥣','food','bowl with spoon|cereal|soup'],
  ['🥗','food','green salad|salad|healthy'],
  ['🍿','food','popcorn|popcorn|movie'],
  ['🧈','food','butter|butter|dairy'],
  ['🧂','food','salt|salt|shaker'],
  ['🥫','food','canned food|can|tin'],
  ['🍱','food','bento box|bento|japanese'],
  ['🍘','food','rice cracker|senbei|cracker'],
  ['🍙','food','rice ball|onigiri|japanese'],
  ['🍚','food','cooked rice|rice|japanese'],
  ['🍛','food','curry rice|curry|japanese'],
  ['🍜','food','steaming bowl|ramen|noodles'],
  ['🍝','food','spaghetti|pasta|italian'],
  ['🍠','food','roasted sweet potato|yam|sweet potato'],
  ['🍢','food','oden|oden|japanese'],
  ['🍣','food','sushi|sushi|japanese'],
  ['🍤','food','fried shrimp|tempura|shrimp'],
  ['🍥','food','fish cake with swirl|naruto|kamaboko'],
  ['🥮','food','moon cake|mooncake|mid-autumn'],
  ['🍡','food','dango|dango|japanese'],
  ['🥟','food','dumpling|dumpling|gyoza'],
  ['🥠','food','fortune cookie|fortune cookie'],
  ['🥡','food','takeout box|takeout|chinese'],
  ['🍦','food','soft ice cream|ice cream|dessert'],
  ['🍧','food','shaved ice|shaved ice|dessert'],
  ['🍨','food','ice cream|ice cream|dessert'],
  ['🍩','food','doughnut|donut|dessert'],
  ['🍪','food','cookie|cookie|dessert'],
  ['🎂','food','birthday cake|cake|birthday'],
  ['🍰','food','shortcake|cake|dessert'],
  ['🧁','food','cupcake|cupcake|dessert'],
  ['🥧','food','pie|pie|dessert'],
  ['🍫','food','chocolate bar|chocolate|candy'],
  ['🍬','food','candy|candy|sweet'],
  ['🍭','food','lollipop|lollipop|candy'],
  ['🍮','food','custard|flan|pudding|dessert'],
  ['🍯','food','honey pot|honey|sweet'],
  ['🍼','food','baby bottle|baby|milk'],
  ['🥛','food','glass of milk|milk|drink'],
  ['☕','food','hot beverage|coffee|tea'],
  ['🫖','food','teapot|tea|teapot'],
  ['🍵','food','teacup without handle|tea|matcha'],
  ['🍶','food','sake|sake|japanese'],
  ['🍾','food','bottle with popping cork|champagne|celebrate'],
  ['🍷','food','wine glass|wine|drink'],
  ['🍸','food','cocktail glass|cocktail|drink'],
  ['🍹','food','tropical drink|tropical|drink'],
  ['🍺','food','beer mug|beer|drink'],
  ['🍻','food','clinking beer mugs|beer|cheers'],
  ['🥂','food','clinking glasses|cheers|celebrate'],
  ['🥃','food','tumbler glass|whiskey|drink'],
  ['🫗','food','pouring liquid|pour|drink'],
  ['🥤','food','cup with straw|soda|drink'],
  ['🧋','food','bubble tea|boba|tea'],
  ['🧃','food','drink box|juice box|drink'],
  ['🧊','food','ice cube|ice|cube'],

  // Travel & Places
  ['🚗','travel','car|automobile|vehicle'],
  ['🚕','travel','taxi|cab|vehicle'],
  ['🚙','travel','suv|vehicle|car'],
  ['🚌','travel','bus|bus|vehicle'],
  ['🚎','travel','trolleybus|bus|vehicle'],
  ['🏎️','travel','racing car|race|formula 1'],
  ['🚓','travel','police car|cop|police'],
  ['🚑','travel','ambulance|medical|emergency'],
  ['🚒','travel','fire engine|fire truck|emergency'],
  ['🚐','travel','minibus|bus|van'],
  ['🚚','travel','delivery truck|truck|delivery'],
  ['🚛','travel','articulated lorry|truck|semi'],
  ['🚜','travel','tractor|tractor|farm'],
  ['🏍️','travel','motorcycle|motorbike|bike'],
  ['🛵','travel','scooter|scooter|moped'],
  ['🛺','travel','auto rickshaw|tuk tuk|rickshaw'],
  ['🚲','travel','bicycle|bike|cycle'],
  ['🛴','travel','kick scooter|scooter'],
  ['🚏','travel','bus stop|bus|stop'],
  ['🛣️','travel','motorway|highway|road'],
  ['🛤️','travel','railway track|train track'],
  ['⛽','travel','fuel pump|gas|gas station'],
  ['🚨','travel','police car light|beacon|emergency'],
  ['🚥','travel','horizontal traffic light|traffic light'],
  ['🚦','travel','vertical traffic light|traffic light'],
  ['🚧','travel','construction|road work|barrier'],
  ['⚓','travel','anchor|ship|boat|nautical'],
  ['🛟','travel','ring buoy|life preserver|float'],
  ['⛵','travel','sailboat|boat|sail'],
  ['🛶','travel','canoe|kayak|boat'],
  ['🚤','travel','speedboat|boat|fast'],
  ['🛳️','travel','passenger ship|ship|cruise'],
  ['⛴️','travel','ferry|ferry|boat'],
  ['🛥️','travel','motor boat|boat|motor'],
  ['🚢','travel','ship|ship|boat'],
  ['✈️','travel','airplane|plane|flight'],
  ['🛩️','travel','small airplane|plane|flight'],
  ['🛫','travel','airplane departure|takeoff|flight'],
  ['🛬','travel','airplane arrival|landing|flight'],
  ['🪂','travel','parachute|parachute|skydive'],
  ['💺','travel','seat|seat|airplane'],
  ['🚁','travel','helicopter|helicopter|chopper'],
  ['🚟','travel','suspension railway|cable car'],
  ['🚠','travel','mountain cableway|cable car'],
  ['🚡','travel','aerial tramway|tram|ski lift'],
  ['🛰️','travel','satellite|satellite|space'],
  ['🚀','travel','rocket|rocket|space|launch'],
  ['🛸','travel','flying saucer|ufo|alien'],
  ['🛎️','travel','bellhop bell|bell|hotel|service'],
  ['🧳','travel','luggage|suitcase|travel'],
  ['⌛','travel','hourglass done|time|timer'],
  ['⏳','travel','hourglass not done|time|waiting'],
  ['⌚','travel','watch|watch|time'],
  ['⏰','travel','alarm clock|alarm|time'],
  ['⏱️','travel','stopwatch|timer|time'],
  ['⏲️','travel','timer clock|timer|time'],
  ['🕰️','travel','mantelpiece clock|clock|time'],
  ['🕛','travel','twelve oclock|12|clock'],
  ['🕐','travel','one oclock|1|clock'],
  ['🕑','travel','two oclock|2|clock'],
  ['🕒','travel','three oclock|3|clock'],
  ['🕓','travel','four oclock|4|clock'],
  ['🕔','travel','five oclock|5|clock'],
  ['🕕','travel','six oclock|6|clock'],
  ['🕖','travel','seven oclock|7|clock'],
  ['🕗','travel','eight oclock|8|clock'],
  ['🕘','travel','nine oclock|9|clock'],
  ['🕙','travel','ten oclock|10|clock'],
  ['🕚','travel','eleven oclock|11|clock'],
  ['🌑','travel','new moon|moon|dark'],
  ['🌒','travel','waxing crescent moon|moon'],
  ['🌓','travel','first quarter moon|moon'],
  ['🌔','travel','waxing gibbous moon|moon'],
  ['🌕','travel','full moon|moon'],
  ['🌖','travel','waning gibbous moon|moon'],
  ['🌗','travel','last quarter moon|moon'],
  ['🌘','travel','waning crescent moon|moon'],
  ['🌑','travel','new moon|moon'],
  ['🌃','travel','night with stars|night|city'],
  ['🏙️','travel','cityscape|city|skyline'],
  ['🌄','travel','sunrise over mountains|sunrise|morning'],
  ['🌅','travel','sunrise|sunrise|morning'],
  ['🌆','travel','cityscape at dusk|city|evening'],
  ['🌇','travel','sunset|sunset|evening'],
  ['🌉','travel','bridge at night|bridge|night'],
  ['🗼','travel','tokyo tower|tokyo|japan'],
  ['🗽','travel','statue of liberty|nyc|new york'],
  ['🏰','travel','castle|castle|princess'],
  ['🏯','travel','japanese castle|castle|japan'],
  ['🏟️','travel','stadium|stadium|sports'],
  ['🎡','travel','ferris wheel|amusement park'],
  ['🎢','travel','roller coaster|amusement park'],
  ['🎠','travel','carousel horse|merry-go-round'],
  ['⛱️','travel','umbrella on ground|beach|umbrella'],
  ['🏖️','travel','beach with umbrella|beach|vacation'],
  ['🏝️','travel','desert island|island|stranded'],
  ['🏜️','travel','desert|desert|arid'],
  ['🏔️','travel','snow-capped mountain|mountain|snow'],
  ['⛰️','travel','mountain|mountain'],
  ['🌋','travel','volcano|volcano|lava'],
  ['🗻','travel','mount fuji|fuji|japan|mountain'],
  ['🏕️','travel','camping|camp|tent'],
  ['🏠','travel','house|house|home'],
  ['🏡','travel','house with garden|house|garden'],
  ['🏢','travel','office building|office|corporate'],
  ['🏣','travel','japanese post office|post office'],
  ['🏤','travel','post office|post|mail'],
  ['🏥','travel','hospital|hospital|medical'],
  ['🏦','travel','bank|bank|finance'],
  ['🏨','travel','hotel|hotel|lodging'],
  ['🏩','travel','love hotel|love hotel'],
  ['🏪','travel','convenience store|store|convenience'],
  ['🏫','travel','school|school|education'],
  ['🏬','travel','department store|store|shopping'],
  ['🏭','travel','factory|factory|industry'],
  ['🏯','travel','japanese castle|castle'],
  ['🏰','travel','castle|castle|european'],

  // Activities
  ['⚽','activities','soccer ball|soccer|football'],
  ['🏀','activities','basketball|basketball|hoops'],
  ['🏈','activities','american football|football|nfl'],
  ['⚾','activities','baseball|baseball|mlb'],
  ['🎾','activities','tennis|tennis|racket'],
  ['🏐','activities','volleyball|volleyball'],
  ['🏉','activities','rugby football|rugby'],
  ['🎱','activities','pool 8 ball|billiards|pool|8 ball'],
  ['🏓','activities','ping pong|table tennis|paddle'],
  ['🏸','activities','badminton|badminton|shuttlecock'],
  ['🥊','activities','boxing glove|boxing|punch'],
  ['🥋','activities','martial arts uniform|karate|judo'],
  ['🥅','activities','goal net|goal|net'],
  ['⛳','activities','flag in hole|golf|hole'],
  ['⛸️','activities','ice skate|skate|ice skating'],
  ['🎣','activities','fishing pole|fishing|angle'],
  ['🤿','activities','diving mask|scuba|dive'],
  ['🎽','activities','running shirt|running|athlete'],
  ['🎿','activities','skis|ski|snow'],
  ['🛷','activities','sled|sled|toboggan'],
  ['🥌','activities','curling stone|curling'],
  ['🎯','activities','direct hit|target|bullseye|darts'],
  ['🪀','activities','yo-yo|yoyo|toy'],
  ['🪁','activities','kite|kite|fly'],
  ['🎮','activities','video game|game|controller'],
  ['🕹️','activities','joystick|retro|arcade'],
  ['🎲','activities','game die|dice|board game'],
  ['♟️','activities','chess pawn|chess|board game'],
  ['🎭','activities','performing arts|theater|mask'],
  ['🎨','activities','artist palette|art|palette|paint'],
  ['🎪','activities','circus tent|circus|carnival'],
  ['🎤','activities','microphone|mic|sing'],
  ['🎧','activities','headphone|headphones|music'],
  ['🎶','activities','musical notes|music|notes'],
  ['🎵','activities','musical note|music|note'],
  ['🎼','activities','musical score|sheet music'],
  ['🎹','activities','musical keyboard|piano|keyboard'],
  ['🥁','activities','drum|drum|percussion'],
  ['🪘','activities','long drum|djembe|drum'],
  ['🎷','activities','saxophone|sax|jazz'],
  ['🎺','activities','trumpet|trumpet|brass'],
  ['🎸','activities','guitar|guitar|rock'],
  ['🪕','activities','banjo|banjo|bluegrass'],
  ['🎻','activities','violin|violin|string'],
  ['🎬','activities','clapper board|film|movie|director'],
  ['📽️','activities','film projector|movie|projector'],
  ['🎥','activities','movie camera|camera|film'],
  ['📺','activities','television|tv|screen'],
  ['📷','activities','camera|camera|photo'],
  ['📸','activities','camera with flash|camera|photo'],
  ['📹','activities','video camera|camcorder|video'],
  ['📼','activities','videocassette|vhs|tape'],
  ['🔍','activities','magnifying glass tilted left|search|zoom'],
  ['🔎','activities','magnifying glass tilted right|search|zoom'],
  ['💡','activities','light bulb|bulb|idea|light'],
  ['🔦','activities','flashlight|torch|light'],
  ['🏮','activities','red paper lantern|lantern|asian'],
  ['📔','activities','notebook with decorative cover|notebook'],
  ['📕','activities','closed book|book|closed'],
  ['📖','activities','open book|book|open'],
  ['📗','activities','green book|book|green'],
  ['📘','activities','blue book|book|blue'],
  ['📙','activities','orange book|book|orange'],
  ['📚','activities','books|books|library'],
  ['📓','activities','notebook|notebook|journal'],
  ['📒','activities','ledger|ledger|notebook'],
  ['📃','activities','page with curl|document|page'],
  ['📜','activities','scroll|scroll|ancient'],
  ['📄','activities','page facing up|document|file'],
  ['📰','activities','newspaper|news|paper'],
  ['🗞️','activities','rolled-up newspaper|news|paper'],
  ['📑','activities','bookmark tabs|bookmark|tabs'],
  ['🔖','activities','bookmark|bookmark|mark'],
  ['🏷️','activities','label|tag|price'],
  ['💰','activities','money bag|money|cash|wealth'],
  ['🪙','activities','coin|coin|money|gold'],
  ['💴','activities','yen banknote|yen|japan|money'],
  ['💵','activities','dollar banknote|dollar|money'],
  ['💶','activities','euro banknote|euro|money'],
  ['💷','activities','pound banknote|pound|money'],
  ['💸','activities','money with wings|money|fly|spend'],
  ['💳','activities','credit card|card|payment'],
  ['🧾','activities','receipt|receipt|invoice'],
  ['💎','activities','gem stone|diamond|gem|jewel'],
  ['⚙️','activities','gear|cog|settings'],
  ['🔧','activities','wrench|tool|fix'],
  ['🛠️','activities','hammer and wrench|tools|fix'],
  ['🔨','activities','hammer|hammer|tool'],
  ['🪓','activities','axe|axe|chop'],
  ['🔩','activities','nut and bolt|screw|hardware'],
  ['⚒️','activities','hammer and pick|tools|mining'],
  ['🛡️','activities','shield|shield|protect'],
  ['🔗','activities','link|link|chain'],
  ['⛓️','activities','chains|chain|linked'],
  ['🪝','activities','hook|hook|catch'],
  ['🧰','activities','toolbox|tools|box'],
  ['🧲','activities','magnet|magnet|attract'],
  ['🪜','activities','ladder|ladder|climb'],
  ['⚗️','activities','alembic|chemistry|distill'],
  ['🧪','activities','test tube|science|lab'],
  ['🧫','activities','petri dish|science|biology'],
  ['🧬','activities','dna|dna|genetics'],
  ['🔬','activities','microscope|science|lab'],
  ['🔭','activities','telescope|space|astronomy'],
  ['📡','activities','satellite antenna|antenna|signal'],
  ['💉','activities','syringe|shot|vaccine|medical'],
  ['🩸','activities','drop of blood|blood|medical'],
  ['💊','activities','pill|medicine|drug'],
  ['🩹','activities','adhesive bandage|bandaid|medical'],
  ['🚪','activities','door|door|exit'],
  ['🛗','activities','elevator|lift'],
  ['🪞','activities','mirror|mirror|reflect'],
  ['🪟','activities','window|window|glass'],
  ['🛏️','activities','bed|bed|sleep'],
  ['🛋️','activities','couch and lamp|sofa|living room'],
  ['🪑','activities','chair|chair|seat'],
  ['🚽','activities','toilet|toilet|bathroom'],
  ['🪠','activities','plunger|plunger|toilet'],
  ['🚿','activities','shower|shower|bath'],
  ['🛁','activities','bathtub|tub|bath'],
  ['🪥','activities','toothbrush|brush|dental'],
  ['🧴','activities','lotion bottle|lotion|cream'],
  ['🧷','activities','safety pin|pin|safety'],
  ['🧹','activities','broom|broom|sweep'],
  ['🧺','activities','basket|basket|laundry'],
  ['🧻','activities','roll of paper|toilet paper|paper'],
  ['🪣','activities','bucket|bucket|pail'],
  ['🧼','activities','soap|soap|clean'],
  ['🫧','activities','bubbles|bubbles|soap'],
  ['🪒','activities','razor|razor|shave'],
  ['🪮','activities','hair pick|comb|hair'],
  ['🧽','activities','sponge|sponge|clean'],
  ['🧯','activities','fire extinguisher|fire|extinguish'],
  ['🛒','activities','shopping cart|cart|shop'],
  ['🗝️','activities','old key|key|antique'],
  ['🔑','activities','key|key|password'],
  ['🔐','activities','locked with key|lock|secure'],
  ['🔒','activities','locked|lock|secure'],
  ['🔓','activities','unlocked|unlock|open'],
  ['🔏','activities','locked with pen|lock|sign'],
  ['🔐','activities','locked with key|lock|secure'],
  ['🛡️','activities','shield|shield|protect'],

  // Symbols
  ['❤️','symbols','red heart|love'],
  ['🧡','symbols','orange heart|love'],
  ['💛','symbols','yellow heart|love'],
  ['💚','symbols','green heart|love'],
  ['💙','symbols','blue heart|love'],
  ['💜','symbols','purple heart|love'],
  ['🖤','symbols','black heart|love'],
  ['🤍','symbols','white heart|love'],
  ['💔','symbols','broken heart|heartbreak'],
  ['❣️','symbols','heart exclamation|love'],
  ['💕','symbols','two hearts|love'],
  ['💞','symbols','revolving hearts|love'],
  ['💓','symbols','beating heart|love'],
  ['💗','symbols','growing heart|love'],
  ['💖','symbols','sparkling heart|love'],
  ['💘','symbols','heart with arrow|love'],
  ['💝','symbols','heart with ribbon|gift|love'],
  ['💟','symbols','heart decoration|love'],
  ['☮️','symbols','peace symbol|peace'],
  ['✝️','symbols','cross|christian|religion'],
  ['☪️','symbols','star and crescent|islam|religion'],
  ['☯️','symbols','yin yang|taoism'],
  ['🕉️','symbols','om|hindu|religion'],
  ['✡️','symbols','star of david|judaism|religion'],
  ['🔯','symbols','six pointed star|star|magi'],
  ['🪯','symbols','khanda|sikhism|religion'],
  ['♾️','symbols','infinity|forever|unlimited'],
  ['♻️','symbols','recycling symbol|recycle|green'],
  ['⚜️','symbols','fleur-de-lis|french|royal'],
  ['🔱','symbols','trident emblem|trident|poseidon'],
  ['📛','symbols','name badge|badge|name'],
  ['🔰','symbols','japanese symbol for beginner|beginner|green'],
  ['⭕','symbols','hollow red circle|circle|o'],
  ['✅','symbols','check mark button|check|yes'],
  ['☑️','symbols','check box with check|checkbox|check'],
  ['✔️','symbols','check mark|check|yes'],
  ['❌','symbols','cross mark|x|no'],
  ['❎','symbols','cross mark button|x|no'],
  ['➰','symbols','curly loop|loop|curly'],
  ['➿','symbols','double curly loop|loop|curly'],
  ['〽️','symbols','part alternation mark|part'],
  ['✳️','symbols','eight-spoked asterisk|asterisk|star'],
  ['✴️','symbols','eight-pointed star|star'],
  ['❇️','symbols','sparkle|sparkle|star'],
  ['‼️','symbols','double exclamation mark|bang|exclaim'],
  ['⁉️','symbols','exclamation question mark|interrobang'],
  ['❓','symbols','question mark|question|help'],
  ['❔','symbols','white question mark|question|help'],
  ['❕','symbols','white exclamation mark|exclaim'],
  ['❗','symbols','exclamation mark|exclaim|bang'],
  ['〰️','symbols','wavy dash|dash|wavy'],
  ['©️','symbols','copyright|copyright'],
  ['®️','symbols','registered|registered|trademark'],
  ['™️','symbols','trade mark|trademark'],
  ['🔴','symbols','red circle|circle|red'],
  ['🟠','symbols','orange circle|circle|orange'],
  ['🟡','symbols','yellow circle|circle|yellow'],
  ['🟢','symbols','green circle|circle|green'],
  ['🔵','symbols','blue circle|circle|blue'],
  ['🟣','symbols','purple circle|circle|purple'],
  ['🟤','symbols','brown circle|circle|brown'],
  ['⚫','symbols','black circle|circle|black'],
  ['⚪','symbols','white circle|circle|white'],
  ['🟥','symbols','red square|square|red'],
  ['🟧','symbols','orange square|square|orange'],
  ['🟨','symbols','yellow square|square|yellow'],
  ['🟩','symbols','green square|square|green'],
  ['🟦','symbols','blue square|square|blue'],
  ['🟪','symbols','purple square|square|purple'],
  ['🟫','symbols','brown square|square|brown'],
  ['⬛','symbols','black large square|square|black'],
  ['⬜','symbols','white large square|square|white'],
  ['🔶','symbols','large orange diamond|diamond|orange'],
  ['🔷','symbols','large blue diamond|diamond|blue'],
  ['🔸','symbols','small orange diamond|diamond|orange'],
  ['🔹','symbols','small blue diamond|diamond|blue'],
  ['🔺','symbols','red triangle pointed up|triangle|red'],
  ['🔻','symbols','red triangle pointed down|triangle|red'],
  ['💠','symbols','diamond with a dot|diamond|kawaii'],
  ['🔘','symbols','radio button|radio|button'],
  ['🔲','symbols','black square button|button|square'],
  ['🔳','symbols','white square button|button|square'],
  ['🔈','symbols','speaker low volume|speaker|sound'],
  ['🔉','symbols','speaker medium volume|speaker|sound'],
  ['🔊','symbols','speaker high volume|speaker|loud'],
  ['🔇','symbols','muted speaker|mute|silent'],
  ['📢','symbols','loudspeaker|speaker|announce'],
  ['📣','symbols','megaphone|megaphone|shout'],
  ['📯','symbols','postal horn|horn|postal'],
  ['🔔','symbols','bell|bell|notification'],
  ['🔕','symbols','bell with slash|bell|mute'],
  ['🎵','symbols','musical note|music|note'],
  ['🎶','symbols','musical notes|music|notes'],
  ['💤','symbols','zzz|sleep|tired'],
  ['💢','symbols','anger symbol|angry|mad'],
  ['💣','symbols','bomb|bomb|explosive'],
  ['💥','symbols','collision|boom|explosion'],
  ['💦','symbols','sweat droplets|sweat|exercise'],
  ['💨','symbols','dashing away|run|speed'],
  ['💫','symbols','dizzy|star|sparkle'],
  ['💬','symbols','speech balloon|chat|talk'],
  ['🗨️','symbols','left speech bubble|chat|talk'],
  ['🗯️','symbols','right anger bubble|angry'],
  ['💭','symbols','thought balloon|think|idea'],
  ['🛐','symbols','place of worship|religion|worship'],
  ['⚛️','symbols','atom symbol|atom|science'],
  ['🆔','symbols','id button|id|identity'],
  ['🈳','symbols','japanese empty button|empty|vacancy'],
  ['🈹','symbols','japanese discount button|discount'],
  ['🈯','symbols','japanese reserved button|reserved'],
  ['🈷️','symbols','japanese monthly amount|monthly'],
  ['🈶','symbols','japanese not free of charge|fee'],
  ['🈚','symbols','japanese free of charge|free'],
  ['🈸','symbols','japanese application button|application'],
  ['🈺','symbols','japanese open for business|open'],
  ['🈴','symbols','japanese passing grade|pass|grade'],
  ['🉐','symbols','japanese bargain button|bargain'],
  ['🉑','symbols','japanese acceptable button|accept'],
  ['🔠','symbols','input latin uppercase|abc|letters'],
  ['🔡','symbols','input latin lowercase|abc|letters'],
  ['🔢','symbols','input numbers|123|numbers'],
  ['🔣','symbols','input symbols|symbols|special'],
  ['🔤','symbols','input latin letters|abc|alphabet'],
  ['🅰️','symbols','a button|a|letter'],
  ['🆎','symbols','ab button|ab|blood'],
  ['🅱️','symbols','b button|b|letter'],
  ['🆑','symbols','cl button|cl|clean'],
  ['🆒','symbols','cool button|cool'],
  ['🆓','symbols','free button|free'],
  ['ℹ️','symbols','information|info|information'],
  ['🆔','symbols','id button|id'],
  ['ⓜ️','symbols','circled m|m|metro'],
  ['🆕','symbols','new button|new|fresh'],
  ['🆖','symbols','ng button|ng|no good'],
  ['🅾️','symbols','o button|o|letter'],
  ['🆗','symbols','ok button|ok|okay'],
  ['🅿️','symbols','p button|parking'],
  ['🆘','symbols','sos button|sos|help'],
  ['🆙','symbols','up button|up'],
  ['🆚','symbols','vs button|vs|versus'],
  ['🈁','symbols','japanese here button|here|koko'],
  ['🈂️','symbols','japanese service charge|service|sa'],
  ['🚻','symbols','restroom|wc|bathroom'],
  ['🚹','symbols','men room|men|male'],
  ['🚺','symbols','women room|women|female'],
  ['🚼','symbols','baby symbol|baby|child'],
  ['🚾','symbols','water closet|wc|toilet'],
  ['♿','symbols','wheelchair|accessibility|handicap'],
  ['🛜','symbols','wireless|wifi|signal'],

  // Flags
  ['🏳️','flags','white flag|flag|white'],
  ['🏴','flags','black flag|flag|black'],
  ['🏁','flags','checkered flag|racing|finish'],
  ['🚩','flags','triangular flag|flag|post'],
  ['🏳️‍🌈','flags','rainbow flag|lgbt|pride|gay'],
  ['🏳️‍⚧️','flags','transgender flag|trans|lgbt'],
  ['🏴‍☠️','flags','pirate flag|pirate|jolly roger'],
  ['🇺🇳','flags','united nations|un|flag'],
  ['🇦🇫','flags','afghanistan|flag'],
  ['🇦🇱','flags','albania|flag'],
  ['🇩🇿','flags','algeria|flag'],
  ['🇦🇩','flags','andorra|flag'],
  ['🇦🇴','flags','angola|flag'],
  ['🇦🇷','flags','argentina|flag'],
  ['🇦🇲','flags','armenia|flag'],
  ['🇦🇺','flags','australia|flag'],
  ['🇦🇹','flags','austria|flag'],
  ['🇦🇿','flags','azerbaijan|flag'],
  ['🇧🇸','flags','bahamas|flag'],
  ['🇧🇭','flags','bahrain|flag'],
  ['🇧🇩','flags','bangladesh|flag'],
  ['🇧🇧','flags','barbados|flag'],
  ['🇧🇾','flags','belarus|flag'],
  ['🇧🇪','flags','belgium|flag'],
  ['🇧🇿','flags','belize|flag'],
  ['🇧🇯','flags','benin|flag'],
  ['🇧🇹','flags','bhutan|flag'],
  ['🇧🇴','flags','bolivia|flag'],
  ['🇧🇦','flags','bosnia and herzegovina|flag'],
  ['🇧🇼','flags','botswana|flag'],
  ['🇧🇷','flags','brazil|flag'],
  ['🇧🇳','flags','brunei|flag'],
  ['🇧🇬','flags','bulgaria|flag'],
  ['🇧🇫','flags','burkina faso|flag'],
  ['🇧🇮','flags','burundi|flag'],
  ['🇰🇭','flags','cambodia|flag'],
  ['🇨🇲','flags','cameroon|flag'],
  ['🇨🇦','flags','canada|flag'],
  ['🇨🇻','flags','cape verde|flag'],
  ['🇨🇫','flags','central african republic|flag'],
  ['🇹🇩','flags','chad|flag'],
  ['🇨🇱','flags','chile|flag'],
  ['🇨🇳','flags','china|flag|cn'],
  ['🇨🇴','flags','colombia|flag'],
  ['🇰🇲','flags','comoros|flag'],
  ['🇨🇬','flags','congo|flag'],
  ['🇨🇩','flags','congo kinshasa|flag'],
  ['🇨🇷','flags','costa rica|flag'],
  ['🇭🇷','flags','croatia|flag'],
  ['🇨🇺','flags','cuba|flag'],
  ['🇨🇾','flags','cyprus|flag'],
  ['🇨🇿','flags','czech republic|flag|czechia'],
  ['🇩🇰','flags','denmark|flag'],
  ['🇩🇯','flags','djibouti|flag'],
  ['🇩🇲','flags','dominica|flag'],
  ['🇩🇴','flags','dominican republic|flag'],
  ['🇪🇨','flags','ecuador|flag'],
  ['🇪🇬','flags','egypt|flag'],
  ['🇸🇻','flags','el salvador|flag'],
  ['🇬🇶','flags','equatorial guinea|flag'],
  ['🇪🇷','flags','eritrea|flag'],
  ['🇪🇪','flags','estonia|flag'],
  ['🇸🇿','flags','eswatini|flag'],
  ['🇪🇹','flags','ethiopia|flag'],
  ['🇫🇯','flags','fiji|flag'],
  ['🇫🇮','flags','finland|flag'],
  ['🇫🇷','flags','france|flag|fr'],
  ['🇬🇦','flags','gabon|flag'],
  ['🇬🇲','flags','gambia|flag'],
  ['🇬🇪','flags','georgia|flag'],
  ['🇩🇪','flags','germany|flag|de'],
  ['🇬🇭','flags','ghana|flag'],
  ['🇬🇷','flags','greece|flag'],
  ['🇬🇩','flags','grenada|flag'],
  ['🇬🇹','flags','guatemala|flag'],
  ['🇬🇳','flags','guinea|flag'],
  ['🇬🇼','flags','guinea-bissau|flag'],
  ['🇬🇾','flags','guyana|flag'],
  ['🇭🇹','flags','haiti|flag'],
  ['🇭🇳','flags','honduras|flag'],
  ['🇭🇺','flags','hungary|flag'],
  ['🇮🇸','flags','iceland|flag'],
  ['🇮🇳','flags','india|flag'],
  ['🇮🇩','flags','indonesia|flag'],
  ['🇮🇷','flags','iran|flag'],
  ['🇮🇶','flags','iraq|flag'],
  ['🇮🇪','flags','ireland|flag'],
  ['🇮🇱','flags','israel|flag'],
  ['🇮🇹','flags','italy|flag|it'],
  ['🇯🇲','flags','jamaica|flag'],
  ['🇯🇵','flags','japan|flag|jp'],
  ['🇯🇴','flags','jordan|flag'],
  ['🇰🇿','flags','kazakhstan|flag'],
  ['🇰🇪','flags','kenya|flag'],
  ['🇰🇮','flags','kiribati|flag'],
  ['🇰🇼','flags','kuwait|flag'],
  ['🇰🇬','flags','kyrgyzstan|flag'],
  ['🇱🇦','flags','laos|flag'],
  ['🇱🇻','flags','latvia|flag'],
  ['🇱🇧','flags','lebanon|flag'],
  ['🇱🇸','flags','lesotho|flag'],
  ['🇱🇷','flags','liberia|flag'],
  ['🇱🇾','flags','libya|flag'],
  ['🇱🇮','flags','liechtenstein|flag'],
  ['🇱🇹','flags','lithuania|flag'],
  ['🇱🇺','flags','luxembourg|flag'],
  ['🇲🇬','flags','madagascar|flag'],
  ['🇲🇼','flags','malawi|flag'],
  ['🇲🇾','flags','malaysia|flag'],
  ['🇲🇻','flags','maldives|flag'],
  ['🇲🇱','flags','mali|flag'],
  ['🇲🇹','flags','malta|flag'],
  ['🇲🇭','flags','marshall islands|flag'],
  ['🇲🇷','flags','mauritania|flag'],
  ['🇲🇺','flags','mauritius|flag'],
  ['🇲🇽','flags','mexico|flag'],
  ['🇫🇲','flags','micronesia|flag'],
  ['🇲🇩','flags','moldova|flag'],
  ['🇲🇨','flags','monaco|flag'],
  ['🇲🇳','flags','mongolia|flag'],
  ['🇲🇪','flags','montenegro|flag'],
  ['🇲🇦','flags','morocco|flag'],
  ['🇲🇿','flags','mozambique|flag'],
  ['🇲🇲','flags','myanmar|flag'],
  ['🇳🇦','flags','namibia|flag'],
  ['🇳🇷','flags','nauru|flag'],
  ['🇳🇵','flags','nepal|flag'],
  ['🇳🇱','flags','netherlands|flag|nl'],
  ['🇳🇿','flags','new zealand|flag|nz'],
  ['🇳🇮','flags','nicaragua|flag'],
  ['🇳🇪','flags','niger|flag'],
  ['🇳🇬','flags','nigeria|flag'],
  ['🇰🇵','flags','north korea|flag|kp'],
  ['🇲🇰','flags','north macedonia|flag'],
  ['🇳🇴','flags','norway|flag'],
  ['🇴🇲','flags','oman|flag'],
  ['🇵🇰','flags','pakistan|flag'],
  ['🇵🇼','flags','palau|flag'],
  ['🇵🇸','flags','palestine|flag'],
  ['🇵🇦','flags','panama|flag'],
  ['🇵🇬','flags','papua new guinea|flag'],
  ['🇵🇾','flags','paraguay|flag'],
  ['🇵🇪','flags','peru|flag'],
  ['🇵🇭','flags','philippines|flag'],
  ['🇵🇱','flags','poland|flag'],
  ['🇵🇹','flags','portugal|flag'],
  ['🇶🇦','flags','qatar|flag'],
  ['🇷🇴','flags','romania|flag'],
  ['🇷🇺','flags','russia|flag|ru'],
  ['🇷🇼','flags','rwanda|flag'],
  ['🇰🇳','flags','saint kitts and nevis|flag'],
  ['🇱🇨','flags','saint lucia|flag'],
  ['🇻🇨','flags','saint vincent|flag'],
  ['🇼🇸','flags','samoa|flag'],
  ['🇸🇲','flags','san marino|flag'],
  ['🇸🇹','flags','sao tome and principe|flag'],
  ['🇸🇦','flags','saudi arabia|flag'],
  ['🇸🇳','flags','senegal|flag'],
  ['🇷🇸','flags','serbia|flag'],
  ['🇸🇨','flags','seychelles|flag'],
  ['🇸🇱','flags','sierra leone|flag'],
  ['🇸🇬','flags','singapore|flag'],
  ['🇸🇰','flags','slovakia|flag'],
  ['🇸🇮','flags','slovenia|flag'],
  ['🇸🇧','flags','solomon islands|flag'],
  ['🇸🇴','flags','somalia|flag'],
  ['🇿🇦','flags','south africa|flag'],
  ['🇰🇷','flags','south korea|flag|kr'],
  ['🇸🇸','flags','south sudan|flag'],
  ['🇪🇸','flags','spain|flag|es'],
  ['🇱🇰','flags','sri lanka|flag'],
  ['🇸🇩','flags','sudan|flag'],
  ['🇸🇷','flags','suriname|flag'],
  ['🇸🇪','flags','sweden|flag'],
  ['🇨🇭','flags','switzerland|flag|ch'],
  ['🇸🇾','flags','syria|flag'],
  ['🇹🇼','flags','taiwan|flag|tw'],
  ['🇹🇯','flags','tajikistan|flag'],
  ['🇹🇿','flags','tanzania|flag'],
  ['🇹🇭','flags','thailand|flag'],
  ['🇹🇱','flags','timor-leste|flag'],
  ['🇹🇬','flags','togo|flag'],
  ['🇹🇴','flags','tonga|flag'],
  ['🇹🇹','flags','trinidad and tobago|flag'],
  ['🇹🇳','flags','tunisia|flag'],
  ['🇹🇷','flags','turkey|flag|tr'],
  ['🇹🇲','flags','turkmenistan|flag'],
  ['🇹🇻','flags','tuvalu|flag'],
  ['🇺🇬','flags','uganda|flag'],
  ['🇺🇦','flags','ukraine|flag'],
  ['🇦🇪','flags','united arab emirates|flag|ae'],
  ['🇬🇧','flags','united kingdom|flag|gb|uk'],
  ['🇺🇸','flags','united states|flag|us|usa'],
  ['🇺🇾','flags','uruguay|flag'],
  ['🇺🇿','flags','uzbekistan|flag'],
  ['🇻🇺','flags','vanuatu|flag'],
  ['🇻🇦','flags','vatican city|flag'],
  ['🇻🇪','flags','venezuela|flag'],
  ['🇻🇳','flags','vietnam|flag'],
  ['🇾🇪','flags','yemen|flag'],
  ['🇿🇲','flags','zambia|flag'],
  ['🇿🇼','flags','zimbabwe|flag'],
];
/**
 * Flat emoji character array for backwards compatibility with icon-picker.js
 */
const EMOJIS = EMOJI_DATA.map(function(e) { return e[0]; });

const LUCIDE_ICONS = ['search', 'clock', 'globe', 'monitor', 'book-open', 'edit-3', 'sword', 'home', 'film', 'shield', 'bar-chart-3', 'container', 'lock', 'github', 'gitlab', 'package', 'code-2', 'message-circle', 'play', 'gamepad-2', 'twitter', 'book', 'settings', 'plus', 'x', 'link', 'star', 'zap', 'flag', 'compass', 'map-pin', 'server', 'database', 'external-link', 'mail', 'music', 'image', 'cpu', 'hard-drive', 'activity', 'wifi', 'radio', 'smartphone', 'tablet', 'laptop', 'watch', 'camera', 'video', 'headphones', 'volume-2', 'monitor-speaker', 'tv', 'layers', 'grid', 'list', 'columns', 'layout', 'panel-top', 'panel-bottom', 'panel-left', 'panel-right', 'square', 'circle', 'triangle', 'hexagon', 'diamond', 'box', 'archive', 'folder', 'file', 'file-text', 'clipboard', 'check-square', 'check', 'x-square', 'trash-2', 'refresh-cw', 'rotate-cw', 'rotate-ccw', 'download', 'upload', 'cloud', 'cloud-drizzle', 'cloud-snow', 'cloud-lightning', 'sun', 'moon', 'thermometer', 'wind', 'droplets', 'umbrella', 'user', 'users', 'user-plus', 'user-check', 'user-x', 'bell', 'bell-ring', 'bell-off', 'eye', 'eye-off', 'lock', 'unlock', 'key', 'fingerprint', 'shield-off', 'alert-triangle', 'alert-circle', 'alert-octagon', 'info', 'help-circle', 'thumbs-up', 'thumbs-down', 'smile', 'frown', 'meh', 'heart', 'calendar', 'calendar-check', 'calendar-x', 'alarm-clock', 'timer', 'hourglass', 'stopwatch', 'map', 'navigation', 'navigation-2', 'crosshair', 'target', 'locate', 'send', 'inbox', 'mail', 'mail-open', 'at-sign', 'phone', 'message-square', 'message-text', 'chat', 'printer', 'scanner', 'bluetooth', 'battery', 'battery-charging', 'power', 'plug', 'bookmark', 'tag', 'award', 'trending-up', 'trending-down', 'pie-chart', 'sliders', 'filter', 'tool', 'wrench', 'hammer', 'paintbrush', 'palette', 'pen-tool', 'eraser', 'scissors', 'copy', 'paste', 'undo', 'redo', 'bold', 'italic', 'underline', 'type', 'hash', 'percent', 'chevron-up', 'chevron-down', 'chevron-left', 'chevron-right', 'chevrons-up', 'chevrons-down', 'chevrons-left', 'chevrons-right', 'arrow-up', 'arrow-down', 'arrow-left', 'arrow-right', 'maximize', 'minimize', 'expand', 'shrink', 'move', 'menu', 'more-horizontal', 'more-vertical', 'sidebar', 'columns', 'rows', 'split', 'sunrise', 'sunset', 'cloud-sun', 'cloud-moon', 'cloudy', 'cloud-off', 'haze', 'mist', 'snowflake', 'sparkles', 'loader', 'radio'];

const EMOJI_TO_LUCIDE={
'🔍':'search','🕐':'clock','🌐':'globe','🖥️':'monitor','📖':'book-open',
'📝':'edit-3','📦':'package','🏠':'home','🎬':'film','🛡️':'shield',
'📊':'bar-chart-3','🐳':'container','🔐':'lock','🐙':'github','🦊':'gitlab',
'📚':'book','🐍':'code-2','💬':'message-circle','▶️':'play','🎮':'gamepad-2',
'🐦':'x','🌍':'globe','⚛️':'atom','📘':'book','⚔️':'sword','🔗':'link',
'⚙️':'settings','🌟':'star','🔥':'flame','💡':'lightbulb','🚀':'rocket',
'⚡':'zap','🎯':'target','🧩':'puzzle','🎨':'palette','📡':'satellite',
'🔧':'wrench','🗄️':'server','💾':'save','🖨️':'printer','📷':'camera',
'🎥':'video','🎵':'music','🎙️':'mic','📻':'radio','📺':'tv','💻':'laptop',
'⌨️':'keyboard','🖱️':'mouse','📱':'smartphone','💽':'disc','💿':'disc',
'📀':'disc','🔌':'plug','🔋':'battery','💎':'diamond','🧊':'snowflake',
'⛅':'cloud-sun','☀️':'sun','🌙':'moon','⭐':'star','✨':'sparkles',
'💫':'star','🎆':'sparkles','🌈':'rainbow','☁️':'cloud','🌊':'waves',
'🔥':'flame','🍃':'wind','🌱':'sprout','🌿':'sprout','☘️':'sprout',
'🍀':'sprout','🏆':'trophy','🥇':'award','🥈':'award','🥉':'award',
'🏅':'award','🎖️':'award','🏁':'flag','🚩':'flag','🎌':'flag',
'📌':'pin','📍':'map-pin','🎪':'tent','🎭':'theater','🎬':'film',
'🎤':'mic','🎧':'headphones','🎼':'music','🎹':'piano','🥁':'drum',
'🎷':'saxophone','🎸':'guitar','🎺':'trumpet','🎻':'violin','🎲':'dice',
'♟️':'chess','🎳':'bowling','🎮':'gamepad-2','🕹️':'joystick','🎰':'slot',
'🧩':'puzzle','♠️':'spade','♥️':'heart','♦️':'diamond','♣️':'club',
'✕':'x','🔄':'refresh-cw','🐍':'code-2'};

function migrateConfigEmojis(cfg){
  if(cfg.branding&&cfg.branding.icon&&EMOJI_TO_LUCIDE[cfg.branding.icon])cfg.branding.icon=EMOJI_TO_LUCIDE[cfg.branding.icon];if(cfg.branding&&cfg.branding.icon==='twitter')cfg.branding.icon='x';
  if(cfg.cards)cfg.cards.forEach(function(card){
    if(card.icon&&EMOJI_TO_LUCIDE[card.icon])card.icon=EMOJI_TO_LUCIDE[card.icon];if(card.icon==='twitter')card.icon='x';
    (card.sections||[]).forEach(function(sec){
      if(sec.type==='links'||sec.type==='link-list')(sec.links||[]).forEach(function(lk){
        if(lk.icon&&EMOJI_TO_LUCIDE[lk.icon])lk.icon=EMOJI_TO_LUCIDE[lk.icon];if(lk.icon==='twitter')lk.icon='x';
      });
    });
  });
}

/* ── Lucide icon utilities ── */
function isLucideName(s){if(!s||typeof s!=='string')return false;if(s.startsWith('http')||s.startsWith('data:')||s.startsWith('/'))return false;if(typeof lucide!=='undefined'&&lucide.icons){const p=s.split('-').map(function(w){return w.charAt(0).toUpperCase()+w.slice(1);}).join('');return p in lucide.icons;}return LUCIDE_ICONS.includes(s);}
function renderLucideEl(name,cls){const i=document.createElement('i');i.className=cls;i.setAttribute('data-lucide',name);return i;}
function renderIcons(){const _lw=console.warn;console.warn=function(){};try{lucide.createIcons();}catch(e){}console.warn=_lw;}

/* ── DOM helpers ── */
const $ = s => document.querySelector(s);
const $$ = s => document.querySelectorAll(s);
function uid(){return Math.random().toString(36).substring(2,9)+Date.now().toString(36);}
function escHtml(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML.replace(/"/g,'&quot;').replace(/'/g,'&#39;');}
function cloneObj(o){return JSON.parse(JSON.stringify(o));}

/* ── Toast ── */
function toast(msg,type='info'){
  // Dedup: skip if an identical toast is already visible
  const existing = document.querySelectorAll('.toast');
  for (var i = 0; i < existing.length; i++) {
    if (existing[i].textContent === msg) return;
  }
  const el=document.createElement('div');el.className=`toast ${type}`;el.textContent=msg;$('#toast-container').appendChild(el);setTimeout(()=>el.remove(),3000);}
function toastWithUndo(msg,undoFn){const el=document.createElement('div');el.className='toast';el.style.cssText='display:flex;align-items:center;gap:10px;';const t=document.createElement('span');t.textContent=msg;const b=document.createElement('button');b.className='btn btn-glass btn-sm';b.textContent='Undo';b.style.fontWeight='700';b.addEventListener('click',()=>{undoFn();el.remove();toast('Restored','success');});el.appendChild(t);el.appendChild(b);$('#toast-container').appendChild(el);setTimeout(()=>el.remove(),5000);}

/* ── Time utilities ── */
function prefersReducedMotion() {
  return window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches;
}
function timeAgo(ts){const s=Math.floor((Date.now()-ts)/1000);if(s<60)return s+'s ago';if(s<3600)return Math.floor(s/60)+'m ago';if(s<86400)return Math.floor(s/3600)+'h ago';return Math.floor(s/86400)+'d ago';}
function getNested(o,p){return p.split('.').reduce((a,pt)=>a&&a[pt],o);}

/* ── Fetch with timeout ── */
function fetchWithTimeout(url, options, timeoutMs) {
  timeoutMs = timeoutMs || 10000;
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  return fetch(url, { ...options, signal: controller.signal }).finally(() => clearTimeout(timer));
}

/* ── Virtual Grid Utilities (coordinate tracking, collision detection) ── */
// Tracks card positions in a virtual coordinate space for future drag-and-drop
// improvements, without changing the current CSS-grid rendering approach.
// Cards are placed left-to-right, top-to-bottom, wrapping per row.
// Each card gets: x, y (column/row start, 1-indexed), cols, rows.

function assignGridPositions(cards, cols) {
  var col=1, row=1;
  cards.forEach(function(c){
    var w=Math.min(c.width||1, cols);
    if(col+w-1>cols){col=1;row+=1;}
    c._gx=col; c._gy=row; c._gw=w; c._gh=Math.min(c.height||1,4);
    col+=w;
  });
}

function getGridBounds(cards, cols) {
  assignGridPositions(cards, cols);
  var gw=cards.reduce(function(m,c){return Math.max(m,c._gx+c._gw-1);},0);
  var gh=cards.reduce(function(m,c){return Math.max(m,c._gy+c._gh-1);},0);
  return {cols:gw, rows:gh};
}

function getCardAt(cards, cols, gx, gy) {
  assignGridPositions(cards, cols);
  for(var i=0;i<cards.length;i++){
    var c=cards[i];
    if(gx>=c._gx&&gx<c._gx+c._gw&&gy>=c._gy&&gy<c._gy+c._gh) return c;
  }
  return null;
}

function isAreaFree(cards, cols, gx, gy, gw, gh, ignoreId) {
  for(var r=0;r<gh;r++)for(var c2=0;c2<gw;c2++){
    var cell=getCardAt(cards,cols,gx+c2,gy+r);
    if(cell&&cell.id!==ignoreId)return false;
  }
  return true;
}